databases:
  - name: cvmanagement-db
    plan: free
    databaseName: cvmanagement
    user: cvmanagement

services:
  - type: web
    name: cvmanagement
    plan: free
    runtime: docker
    repo: https://github.com/Samarth6840/Cvmanagement
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: CONNECTIONSTRINGS__DEFAULTCONNECTION
        fromDatabase:
          name: cvmanagement-db
          property: connectionString
      - key: ASPNETCORE_ENVIRONMENT
        value: production
      - key: Authentication__Google__ClientId
        sync: false
      - key: Authentication__Google__ClientSecret
        sync: false
      - key: Authentication__GitHub__ClientId
        sync: false
      - key: Authentication__GitHub__ClientSecret
        sync: false
      - key: Cloudinary__CloudName
        sync: false
      - key: Cloudinary__ApiKey
        sync: false
      - key: Cloudinary__ApiSecret
        sync: false